### ISSUE TITLE
[mlish] type->str uses the type variable name, instead of the instantiated type

### ISSUE THREAD

**Issue by SuzanneSoy** [stchang/macrotypes#28]
```
#lang s-exp turnstile/examples/mlish
(define (f [x : X] [g : (→ X Y)] -> Y) (g x))
(ann (λ ([a : Int]) (f a number->string)) : Int)
```

The error message (obtained via `type->str`, this has nothing to do with `ann` itself) is `expected Int, given (→ Int Y)`, but should be `expected Int, given (→ Int String)`.

I feel that this is simply an `add-orig` missing on [`τ_out*` in `mlish:#%app`](https://github.com/stchang/macrotypes/blob/34da832e0ed121b5df62ca388c98e79667c1d916/turnstile/examples/mlish.rkt#L917), but I'm not sure how to perform the `Y ↦ Int` substitution on the "pretty" type, without using the internal representation (the one returned by `(current-type-eval)`).

Any hint on how I should fix that issue?

**Comment by stchang** [comment]
Short answer: this is a problem and we don't have a good solution

Longer answer: You can't easily `inst` the `orig` because the type variables in the `orig` have not received all the scopes during expansion and thus are no longer bound by the expanded version of the type variables.

Here is our current hack of a solution, where we give up and just use symbol equality to `inst` the `orig`:
https://github.com/stchang/macrotypes/blob/master/macrotypes/type-constraints.rkt#L175-L177

I've tried using `delta-introducers` on the orig but could not come up with something that works in all caes (ie, makes all the tests pass).

A more drastic alternative I've considered is to give up completely on the `orig` property and instead infer the surface syntax directly from the internal representation (this will probably require re-designing the internal representation), but I have not gotten around to trying this.

**Comment by stchang** [comment]
moved to https://github.com/stchang/mlish/issues/4
